### ISSUE TITLE
Sub-addressing with Postfix does not work

### ISSUE THREAD

**Issue by salaun-urennes1** [sympa-community/sympa-ansible#19] opened 2018-05-27 19:28 UTC
Hi,

Ansible installs /etc/mail/sympa_aliases including : `bounce+*: "| /usr/local/sympa/bin/bouncequeue sympa@lists.example.com"`. On my local server delivery to bounce+* fails with the following error : 
```
May 27 21:07:06 localhost postfix/local[6077]: 0424BA23A6: to=<bounce+3@lists.example.com>, relay=local, delay=1.9, delays=1.9/0.01/0/0, dsn=5.1.1, status=bounced (unknown user: "bounce")
```

I tried applying the recommended change on `/etc/postfix/master.cf` from http://cweiske.de/tagebuch/postfix-plus-addressing.htm but still mails to bounce+* are rejected.

Any clue to fix that?

**Comment by dverdin** [comment] 2018-10-03 12:55
I'm on it! Fix coming soon!

**Comment by racke** [comment] 2018-12-01 11:49
@dverdin Any news on the fix?

**Comment by dverdin** [comment] 2019-01-24 14:00
Oh, the fix is in PR #37 . Forgot to keep you updated about it. Sorry.

**Comment by racke** [comment] 2019-01-24 14:36
It is possible to extract that fix from your humongous PR ?

**Comment by dverdin** [comment] 2019-01-24 14:44
Certainly !
But first, define humongous.

**Comment by racke** [comment] 2019-01-24 14:47
Very large - so would you please add a new PR just with the fix needed for this issue?

**Comment by dverdin** [comment] 2019-01-24 15:06
Actually, it is based on a full revamp of postfix configuration. So I don't think I can extract it simply; without adding first the postfix role and all changes to sympa_mail.pl AND the canges to virtual hosts handling.
However, I can point where in the future code, the problem is fixed.
It is here:

      bounce@{{ item }}         sympabounce:sympa@{{ item }}

https://github.com/dverdin/sympa-ansible/blob/ce255c7b10f348817841e59047c36df7238efcf0/roles/sympa/tasks/sympa_mail.yml#L68

We simply added the missing alias. It is added for all virtual hosts.

**Comment by dverdin** [comment] 2019-03-01 19:37
Fixed!

**Closed as completed by dverdin** 2019-03-01 19:37 UTC
